[package]

name = "compiler_select"
version = "0.0.1"
authors = ["Dylan McKay <me@dylanmckay.io>"]

[dependencies.compiler_mir]
path = "../mir"
[dependencies.compiler_util]
path = "../util"

[lib]
name = "compiler_select"
path = "lib.rs"

